package Model.Entities;
// Generated 11-29-2017 08:34:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer clienteId;
     private String nombre;
     private String apellido;
     private Character genero;
     private String telefono;
     private Date fechaIngreso;
     private String correoElectronico;
     private String ciudad;
     private String domicilio;
     private Set<Ventas> ventases = new HashSet<Ventas>(0);

    public Clientes() {
    }

    public Clientes(String nombre, String apellido, Character genero, String telefono, Date fechaIngreso, String correoElectronico, String ciudad, String domicilio, Set<Ventas> ventases) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.genero = genero;
       this.telefono = telefono;
       this.fechaIngreso = fechaIngreso;
       this.correoElectronico = correoElectronico;
       this.ciudad = ciudad;
       this.domicilio = domicilio;
       this.ventases = ventases;
    }
   
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Character getGenero() {
        return this.genero;
    }
    
    public void setGenero(Character genero) {
        this.genero = genero;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }




}


