package Model.Entities;
// Generated 11-29-2017 08:34:07 PM by Hibernate Tools 4.3.1



/**
 * Detalleventas generated by hbm2java
 */
public class Detalleventas  implements java.io.Serializable {

     private Integer detalleVentaId;
     private Productos productos;
     private Ventas ventas;
     private int cantidad;

    public Detalleventas() {
        this.ventas = new Ventas();
    }

    public Detalleventas(Productos productos, Ventas ventas, int cantidad) {
       this.productos = productos;
       this.ventas = ventas;
       this.cantidad = cantidad;
    }
   
    public Integer getDetalleVentaId() {
        return this.detalleVentaId;
    }
    
    public void setDetalleVentaId(Integer detalleVentaId) {
        this.detalleVentaId = detalleVentaId;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


