package Model.Entities;
// Generated 11-29-2017 08:34:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer productoId;
     private String nombre;
     private BigDecimal precio;
     private Date fechaIngreso;
     private String descripcion;
     private int existencias;
     private String dirImg;
     private Set<Proveedores> proveedoreses = new HashSet<Proveedores>(0);
     private Set<Detalleventas> detalleventases = new HashSet<Detalleventas>(0);

    public Productos() {
    }

	
    public Productos(String nombre, BigDecimal precio, int existencias) {
        this.nombre = nombre;
        this.precio = precio;
        this.existencias = existencias;
    }
    public Productos(String nombre, BigDecimal precio, Date fechaIngreso, String descripcion, int existencias, String dirImg, Set<Proveedores> proveedoreses, Set<Detalleventas> detalleventases) {
       this.nombre = nombre;
       this.precio = precio;
       this.fechaIngreso = fechaIngreso;
       this.descripcion = descripcion;
       this.existencias = existencias;
       this.dirImg = dirImg;
       this.proveedoreses = proveedoreses;
       this.detalleventases = detalleventases;
    }
   
    public Integer getProductoId() {
        return this.productoId;
    }
    
    public void setProductoId(Integer productoId) {
        this.productoId = productoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(int existencias) {
        this.existencias = existencias;
    }
    public String getDirImg() {
        return this.dirImg;
    }
    
    public void setDirImg(String dirImg) {
        this.dirImg = dirImg;
    }
    public Set<Proveedores> getProveedoreses() {
        return this.proveedoreses;
    }
    
    public void setProveedoreses(Set<Proveedores> proveedoreses) {
        this.proveedoreses = proveedoreses;
    }
    public Set<Detalleventas> getDetalleventases() {
        return this.detalleventases;
    }
    
    public void setDetalleventases(Set<Detalleventas> detalleventases) {
        this.detalleventases = detalleventases;
    }




}


