package Model.Entities;
// Generated 11-29-2017 08:34:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private Integer ventaId;
     private Clientes clientes;
     private Empleados empleados;
     private String codigo;
     private BigDecimal totalVenta;
     private Date fechaVenta;
     private Set<Detalleventas> detalleventases = new HashSet<Detalleventas>(0);

    public Ventas() {
        detalleventases = new HashSet<Detalleventas>(0);
    }

    
    public Ventas(Clientes clientes, Empleados empleados, String codigo, Date fechaVenta) {
        this.clientes = clientes;
        this.empleados = empleados;
        this.codigo = codigo;
        this.fechaVenta = fechaVenta;
    }
    public Ventas(Clientes clientes, Empleados empleados, String codigo, BigDecimal totalVenta, Date fechaVenta, Set<Detalleventas> detalleventases) {
       this.clientes = clientes;
       this.empleados = empleados;
       this.codigo = codigo;
       this.totalVenta = totalVenta;
       this.fechaVenta = fechaVenta;
       this.detalleventases = detalleventases;
    }
   
    public Integer getVentaId() {
        return this.ventaId;
    }
    
    public void setVentaId(Integer ventaId) {
        this.ventaId = ventaId;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public BigDecimal getTotalVenta() {
        return this.totalVenta;
    }
    
    public void setTotalVenta(BigDecimal totalVenta) {
        this.totalVenta = totalVenta;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Set<Detalleventas> getDetalleventases() {
        return this.detalleventases;
    }
    
    public void setDetalleventases(Set<Detalleventas> detalleventases) {
        this.detalleventases = detalleventases;
    }
    public void setTotalVenta(float VentaTotal) {
        BigDecimal value = new BigDecimal(Float.toString(VentaTotal));
        this.totalVenta = value;
    }





}


